name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: "Ubuntu Clang 17", os: ubuntu-24.04, toolchain: clang-17, clang_version: 17, installed_clang_version: 14}
          - {name: "Ubuntu Clang 18", os: ubuntu-24.04, toolchain: clang-18, clang_version: 18, installed_clang_version: 14}
          - {name: "Ubuntu GCC 13", os: ubuntu-24.04, toolchain: gcc-13, clang_version: 17, installed_clang_version: 14}
          - {name: "Ubuntu GCC 14", os: ubuntu-24.04, toolchain: gcc-14, clang_version: 17, installed_clang_version: 14}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Activate verbose shell
        run: set -x
      - name: Install LLVM+Clang
        if: startsWith(matrix.config.name, 'Ubuntu Clang')
        run: |
          set -x
          cat /etc/lsb-release
          sudo apt-get remove clang-${{matrix.config.installed_clang_version}} \
            lldb-${{matrix.config.installed_clang_version}} \
            lld-${{matrix.config.installed_clang_version}} \
            clangd-${{matrix.config.installed_clang_version}} \
            clang-tidy-${{matrix.config.installed_clang_version}} \
            clang-format-${{matrix.config.installed_clang_version}} \
            clang-tools-${{matrix.config.installed_clang_version}} \
            llvm-${{matrix.config.installed_clang_version}}-dev \
            lld-${{matrix.config.installed_clang_version}} \
            lldb-${{matrix.config.installed_clang_version}} \
            llvm-${{matrix.config.installed_clang_version}}-tools \
            libomp-${{matrix.config.installed_clang_version}}-dev \
            libc++-${{matrix.config.installed_clang_version}}-dev \
            libc++abi-${{matrix.config.installed_clang_version}}-dev \
            libclang-common-${{matrix.config.installed_clang_version}}-dev \
            libclang-${{matrix.config.installed_clang_version}}-dev \
            libclang-cpp${{matrix.config.installed_clang_version}}-dev \
            libunwind-${{matrix.config.installed_clang_version}}-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{matrix.config.clang_version}} all
          sudo apt-get install libc++-dev libc++1 libc++abi-dev libc++abi1
      - name: Install GCC
        if: startsWith(matrix.config.name, 'Ubuntu GCC')
        run: |
          set -x
          cat /etc/lsb-release
          sudo apt update
          sudo apt-get install ${{matrix.config.toolchain}}
      - name: Run tests
        run: |
          set -x
          pwd
          ls -l scripts/run-tests.sh
          scripts/run-tests.sh --fresh --preset ${{matrix.config.toolchain}} --verbose
